module Fast  
  class ScriptGenerator    
    def self.strip_heredoc(string)
      indent = string.scan(/^[ \t]*(?=\S)/).min.size || 0
      string.gsub(/^[ \t]{#{indent}}/, '')
    end
    
    SCRIPT_BEGIN = strip_heredoc(<<-BASH).freeze
      #This is generated by fast
    BASH
        
    def initialize(host_scripts_dir, container_host_scripts_dir, customized_config)
      @host_scripts_dir = host_scripts_dir
      @container_host_scripts_dir = container_host_scripts_dir
      @customized_config = customized_config
    end
    
    def parse_customized_config(key)
      script = []
      if value = String.try_convert(@customized_config[key]) 
        script = [value]
      elsif value = Array.try_convert(@customized_config[key]) 
        script = value
      end
      script
    end
        
    def generate_script(key, commands = [])
      script = []
      script << SCRIPT_BEGIN
      script << "set -ex"
      script += commands
      script += parse_customized_config(key)
      File.open(File.join(@host_scripts_dir, key), 'w') { |f| f.puts(script.join("\n"))}
      File.join(@container_host_scripts_dir, key)
    end
  end
end